fix logic

diff --git a/bin/steps/python b/bin/steps/python
--- a/bin/steps/python
+++ b/bin/steps/python
@@ -82,7 +82,7 @@ case "${PYTHON_VERSION}" in
     puts-step "Installing PyPy 2.7"
     mkdir -p .heroku/python
 
-    if ! curl --silent --show-error --fail --retry 3 --retry-connrefused --connect-timeout 10 "${PYTHON_URL}" | tar -jxC .heroku/python; then
+    if ! curl --silent --show-error --fail --retry 3 --retry-connrefused --connect-timeout 10 "${PYTHON_URL}" | tar -jfxC .heroku/python; then
       puts-warn "Failed to download/install ${PYTHON_VERSION}"
       exit 1
     fi
@@ -143,15 +143,22 @@ else
   # Prepare destination directory.
   mkdir -p .heroku/python
 
-  if ! curl --silent --show-error --fail --retry 3 --retry-connrefused --connect-timeout 10 "${PYTHON_URL}" | tar -zxC .heroku/python; then
-    # The Python version was confirmed to exist previously, so any failure here is due to
-    # a networking issue or archive/buildpack bug rather than the runtime not existing.
-    puts-warn "Failed to download/install ${PYTHON_VERSION}"
-    exit 1
-  fi
   
   if [[ "${PYTHON_VERSION}" == "pypy-2.7"* ]]; then
+    if ! curl --silent --show-error --fail --retry 3 --retry-connrefused --connect-timeout 10 "${PYTHON_URL}" | tar -xjfC .heroku/python; then
+      # The Python version was confirmed to exist previously, so any failure here is due to
+      # a networking issue or archive/buildpack bug rather than the runtime not existing.
+      puts-warn "Failed to download/install ${PYTHON_VERSION}"
+      exit 1
+    fi
     ln -s .heroku/python/${PYPY_VERSION}-linux64/bin/pypy .heroku/python/bin/python
+  else
+    if ! curl --silent --show-error --fail --retry 3 --retry-connrefused --connect-timeout 10 "${PYTHON_URL}" | tar -zxC .heroku/python; then
+      # The Python version was confirmed to exist previously, so any failure here is due to
+      # a networking issue or archive/buildpack bug rather than the runtime not existing.
+      puts-warn "Failed to download/install ${PYTHON_VERSION}"
+      exit 1
+    fi
   fi
 
   # Record for future reference.
