added pypy2.7 support

diff --git a/bin/steps/python b/bin/steps/python
--- a/bin/steps/python
+++ b/bin/steps/python
@@ -9,7 +9,13 @@ runtime-fixer runtime.txt || true
 PYTHON_VERSION=$(cat runtime.txt)
 
 # The location of the pre-compiled python binary.
-PYTHON_URL="${S3_BASE_URL}/${STACK}/runtimes/${PYTHON_VERSION}.tar.gz"
+# Updated to check if it's pypy
+if [[ "${PYTHON_VERSION}" == "pypy-2.7"* ]]; then
+  PYPY_VERSION=$(echo "${PYTHON_VERSION}" | cut -d '-' -f 2)
+  PYTHON_URL="https://downloads.python.org/pypy/${PYPY_VERSION}-linux64.tar.bz2"
+else
+  PYTHON_URL="${S3_BASE_URL}/${STACK}/runtimes/${PYTHON_VERSION}.tar.gz"
+fi
 
 if ! curl --output /dev/null --silent --head --fail --retry 3 --retry-connrefused --connect-timeout 10 "${PYTHON_URL}"; then
   puts-warn "Requested runtime '${PYTHON_VERSION}' is not available for this stack (${STACK})."
@@ -71,15 +77,21 @@ case "${PYTHON_VERSION}" in
   python-3.6.*)
     eol_python_version_error "3.6" "December 23rd, 2021"
     ;;
-  pypy*)
-    puts-warn
-    puts-warn "PyPy is no longer supported by the latest version of this buildpack."
-    puts-warn
-    puts-warn "Please switch to one of the supported CPython versions by updating your"
-    puts-warn "runtime.txt file. See:"
-    puts-warn "https://devcenter.heroku.com/articles/python-support"
-    puts-warn
-    exit 1
+  pypy-2.7.*)
+    puts-step "Installing PyPy 2.7"
+    mkdir -p .heroku/python
+
+    if ! curl --silent --show-error --fail --retry 3 --retry-connrefused --connect-timeout 10 "${PYTHON_URL}" | tar -jxC .heroku/python; then
+      puts-warn "Failed to download/install ${PYTHON_VERSION}"
+      exit 1
+    fi
+
+    ln -s .heroku/python/${PYPY_VERSION}-linux64/bin/pypy .heroku/python/bin/python
+
+    echo "$PYTHON_VERSION" > .heroku/python-version
+    echo "$STACK" > .heroku/python-stack
+
+    hash -r
     ;;
 esac
 
@@ -135,6 +147,10 @@ else
     # a networking issue or archive/buildpack bug rather than the runtime not existing.
     puts-warn "Failed to download/install ${PYTHON_VERSION}"
     exit 1
+  fi
+  
+  if [[ "${PYTHON_VERSION}" == "pypy-2.7"* ]]; then
+    ln -s .heroku/python/${PYPY_VERSION}-linux64/bin/pypy .heroku/python/bin/python
   fi
 
   # Record for future reference.
